//! Rust port of the production hedge decision core
//! (`src/modules/hedgeController.ts`, ADR-017/018/022 + BUG-012/013 fixes).
//!
//! This must stay behaviorally IDENTICAL to the TypeScript original: the
//! shared test vectors in `fixtures/hedge-vectors.jsonl` (generated by
//! `scripts/export-hedge-vectors.ts` from the production code) are replayed
//! by `tests/vectors.rs` and every decision must match. If you change the
//! TS controller, regenerate the fixtures and fix this port until green —
//! never the other way around: TypeScript is the source of truth, it trades
//! real money.

pub const EPSILON_SOL: f64 = 1e-9;
pub const MIN_HEDGE_INCREASE_USD: f64 = 10.0;

#[derive(Debug, Clone, serde::Deserialize)]
pub struct HedgeInput {
    pub lp_sol: f64,
    pub long_sol: f64,
    pub short_sol: f64,
    pub long_notional_usd: f64,
    pub short_notional_usd: f64,
    pub long_collateral_usd: f64,
    pub short_collateral_usd: f64,
    pub carry_cost_bps_long: f64,
    pub carry_cost_bps_short: f64,
    /// `None` encodes the TS `NaN` case (JSON cannot carry NaN).
    pub oracle_price_usd: Option<f64>,
    pub wallet_sol: f64,
    pub wallet_reserve_sol: f64,
    pub wallet_usdc: f64,
    pub target_delta_sol: f64,
    pub band_sol: f64,
    pub carry_cap_bps: f64,
    pub max_hedge_notional_usd: f64,
    pub min_collateral_ratio: f64,
    pub target_collateral_ratio: f64,
    pub now_ms: i64,
    pub last_action_at_ms: Option<i64>,
    pub cooldown_ms: i64,
}

#[derive(Debug, Clone, PartialEq)]
pub enum Decision {
    None { reason: String },
    Blocked { reason: String },
    DecreaseLong { size_usd: f64, entire_position: bool, withdraw_collateral_usd: f64, adjust_sol: f64 },
    DecreaseShort { size_usd: f64, entire_position: bool, withdraw_collateral_usd: f64, adjust_sol: f64 },
    IncreaseLong { size_usd: f64, collateral_tokens: f64, adjust_sol: f64 },
    IncreaseShort { size_usd: f64, collateral_tokens: f64, adjust_sol: f64 },
}

impl Decision {
    pub fn action(&self) -> &'static str {
        match self {
            Decision::None { .. } => "none",
            Decision::Blocked { .. } => "blocked",
            Decision::DecreaseLong { .. } => "decrease_long",
            Decision::DecreaseShort { .. } => "decrease_short",
            Decision::IncreaseLong { .. } => "increase_long",
            Decision::IncreaseShort { .. } => "increase_short",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq)]
enum Side {
    Long,
    Short,
}

pub fn decide(input: &HedgeInput) -> Decision {
    let price = input.oracle_price_usd.unwrap_or(f64::NAN);
    if !(price > 0.0) || !price.is_finite() {
        return Decision::Blocked { reason: "no oracle SOL price available".into() };
    }

    let net_delta = input.lp_sol + input.long_sol - input.short_sol;
    let error = net_delta - input.target_delta_sol;

    if error.abs() <= input.band_sol {
        return Decision::None { reason: "in band".into() };
    }

    if let Some(last) = input.last_action_at_ms {
        if input.cooldown_ms > 0 {
            let elapsed = input.now_ms - last;
            if elapsed < input.cooldown_ms {
                return Decision::None { reason: "cooldown".into() };
            }
        }
    }

    if error > 0.0 {
        // Too much delta → decrease the long first, else grow the short.
        if input.long_sol > EPSILON_SOL {
            let adjust = error.min(input.long_sol);
            let entire = adjust >= input.long_sol - EPSILON_SOL;
            let size_usd = adjust * price;
            return Decision::DecreaseLong {
                size_usd,
                entire_position: entire,
                withdraw_collateral_usd: if entire { 0.0 } else { size_usd * input.target_collateral_ratio },
                adjust_sol: -adjust,
            };
        }
        return guard_increase(input, Side::Short, error, price);
    }

    let deficit = -error;
    if input.short_sol > EPSILON_SOL {
        let adjust = deficit.min(input.short_sol);
        let entire = adjust >= input.short_sol - EPSILON_SOL;
        let size_usd = adjust * price;
        return Decision::DecreaseShort {
            size_usd,
            entire_position: entire,
            withdraw_collateral_usd: if entire { 0.0 } else { size_usd * input.target_collateral_ratio },
            adjust_sol: adjust,
        };
    }
    guard_increase(input, Side::Long, deficit, price)
}

fn guard_increase(input: &HedgeInput, side: Side, mut adjust_sol: f64, price: f64) -> Decision {
    let carry_cost = match side {
        Side::Long => input.carry_cost_bps_long,
        Side::Short => input.carry_cost_bps_short,
    };
    if input.carry_cap_bps > 0.0 && carry_cost > input.carry_cap_bps {
        return Decision::Blocked { reason: "carry above cap".into() };
    }

    // BUG-012: fill the remaining notional-cap headroom instead of blocking.
    let current_notional = match side {
        Side::Long => input.long_notional_usd,
        Side::Short => input.short_notional_usd,
    };
    let mut size_usd = adjust_sol * price;
    let headroom = input.max_hedge_notional_usd - current_notional;
    if size_usd > headroom {
        if headroom < MIN_HEDGE_INCREASE_USD {
            return Decision::Blocked { reason: "notional headroom below minimum increase".into() };
        }
        size_usd = headroom;
        adjust_sol = size_usd / price;
    }

    // BUG-013: the collateral must physically exist — fill the affordable size.
    let available_collateral = match side {
        Side::Short => input.wallet_usdc.max(0.0),
        Side::Long => ((input.wallet_sol - input.wallet_reserve_sol) * price).max(0.0),
    };
    if size_usd * input.target_collateral_ratio > available_collateral {
        let affordable = available_collateral / input.target_collateral_ratio;
        if affordable < MIN_HEDGE_INCREASE_USD {
            return Decision::Blocked { reason: "collateral affords less than minimum increase".into() };
        }
        size_usd = affordable;
        adjust_sol = size_usd / price;
    }

    let projected_notional = current_notional + size_usd;
    let collateral_usd = size_usd * input.target_collateral_ratio;
    let current_collateral = match side {
        Side::Long => input.long_collateral_usd,
        Side::Short => input.short_collateral_usd,
    };
    let projected_ratio = if projected_notional > 0.0 {
        (current_collateral + collateral_usd) / projected_notional
    } else {
        f64::INFINITY
    };
    if projected_ratio < input.min_collateral_ratio {
        return Decision::Blocked { reason: "projected collateral ratio below floor".into() };
    }

    match side {
        Side::Long => {
            let collateral_sol =
                (collateral_usd / price).min((input.wallet_sol - input.wallet_reserve_sol).max(0.0));
            Decision::IncreaseLong { size_usd, collateral_tokens: collateral_sol, adjust_sol }
        }
        Side::Short => Decision::IncreaseShort {
            size_usd,
            collateral_tokens: collateral_usd,
            adjust_sol: -adjust_sol,
        },
    }
}

// ---------------------------------------------------------------------------
// LP hedge-input transforms (ADR-019/021/023) — ports of computeLpMidpointSol,
// computeLpHedgeDelta and computeAutoNotionalCapUsd.
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum LpRegime {
    Below,
    In,
    Above,
}

pub fn lp_midpoint_sol(lp_sol: f64, lp_usdc: f64, price: f64) -> f64 {
    if !(price > 0.0) {
        return lp_sol;
    }
    (lp_sol + lp_usdc / price) / 2.0
}

pub fn lp_delta_for_regime(regime: LpRegime, lp_sol: f64, lp_usdc: f64, price: f64) -> f64 {
    match regime {
        LpRegime::Below => lp_sol,
        LpRegime::Above => 0.0,
        LpRegime::In => lp_midpoint_sol(lp_sol, lp_usdc, price),
    }
}

/// Hysteresis 98/90 (enter/exit below) and 2/10 (enter/exit above) on the
/// SOL share of position value — identical to `computeLpHedgeDelta`.
pub fn lp_hedge_regime(lp_sol: f64, lp_usdc: f64, price: f64, sticky: LpRegime) -> LpRegime {
    if !(price > 0.0) {
        return sticky;
    }
    let sol_value = lp_sol * price;
    let total = sol_value + lp_usdc;
    if total <= 0.0 {
        return LpRegime::In;
    }
    let share = sol_value / total;
    match sticky {
        LpRegime::Below => {
            if share >= 0.9 {
                LpRegime::Below
            } else if share <= 0.02 {
                LpRegime::Above
            } else {
                LpRegime::In
            }
        }
        LpRegime::Above => {
            if share <= 0.1 {
                LpRegime::Above
            } else if share >= 0.98 {
                LpRegime::Below
            } else {
                LpRegime::In
            }
        }
        LpRegime::In => {
            if share >= 0.98 {
                LpRegime::Below
            } else if share <= 0.02 {
                LpRegime::Above
            } else {
                LpRegime::In
            }
        }
    }
}

/// ADR-022 auto notional cap.
pub fn auto_notional_cap_usd(cap_bag_sol: f64, price: f64, cap_mult: f64, absolute_cap_usd: f64) -> f64 {
    let auto = cap_bag_sol * price * cap_mult;
    if !auto.is_finite() || auto <= 0.0 {
        return if absolute_cap_usd > 0.0 { absolute_cap_usd } else { 0.0 };
    }
    if absolute_cap_usd > 0.0 {
        auto.min(absolute_cap_usd)
    } else {
        auto
    }
}
