//! Replay the shared test vectors generated by the PRODUCTION TypeScript
//! controller (`scripts/export-hedge-vectors.ts`) and demand identical
//! decisions from the Rust port. One truth table, two executors — this is
//! the simulator's authenticity check for decision logic (stage 2, task #7).

use dlmm_simulator::hedge::{decide, Decision, HedgeInput};

#[derive(serde::Deserialize)]
struct Expected {
    action: String,
    size_usd: Option<f64>,
    entire_position: Option<bool>,
    withdraw_collateral_usd: Option<f64>,
    collateral_tokens: Option<f64>,
    adjust_sol: Option<f64>,
}

#[derive(serde::Deserialize)]
struct Vector {
    input: HedgeInput,
    decision: Expected,
}

fn close(a: f64, b: f64) -> bool {
    let scale = a.abs().max(b.abs()).max(1.0);
    (a - b).abs() <= 1e-9 * scale
}

#[test]
fn rust_port_matches_all_production_vectors() {
    let raw = std::fs::read_to_string(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/fixtures/hedge-vectors.jsonl"
    ))
    .expect("fixtures missing — run: npx tsx scripts/export-hedge-vectors.ts");

    let mut checked = 0usize;
    for (line_no, line) in raw.lines().enumerate() {
        if line.trim().is_empty() {
            continue;
        }
        let v: Vector = serde_json::from_str(line).unwrap_or_else(|e| panic!("line {}: {e}", line_no + 1));
        let got = decide(&v.input);
        let ctx = format!("vector at line {} (expected {})", line_no + 1, v.decision.action);

        assert_eq!(got.action(), v.decision.action, "{ctx}: got {}", got.action());
        match &got {
            Decision::None { .. } | Decision::Blocked { .. } => {}
            Decision::DecreaseLong { size_usd, entire_position, withdraw_collateral_usd, adjust_sol }
            | Decision::DecreaseShort { size_usd, entire_position, withdraw_collateral_usd, adjust_sol } => {
                assert!(close(*size_usd, v.decision.size_usd.unwrap()), "{ctx}: size {size_usd}");
                assert_eq!(*entire_position, v.decision.entire_position.unwrap(), "{ctx}: entire");
                assert!(
                    close(*withdraw_collateral_usd, v.decision.withdraw_collateral_usd.unwrap()),
                    "{ctx}: withdraw {withdraw_collateral_usd}"
                );
                assert!(close(*adjust_sol, v.decision.adjust_sol.unwrap()), "{ctx}: adjust {adjust_sol}");
            }
            Decision::IncreaseLong { size_usd, collateral_tokens, adjust_sol }
            | Decision::IncreaseShort { size_usd, collateral_tokens, adjust_sol } => {
                assert!(close(*size_usd, v.decision.size_usd.unwrap()), "{ctx}: size {size_usd}");
                assert!(
                    close(*collateral_tokens, v.decision.collateral_tokens.unwrap()),
                    "{ctx}: collateral {collateral_tokens}"
                );
                assert!(close(*adjust_sol, v.decision.adjust_sol.unwrap()), "{ctx}: adjust {adjust_sol}");
            }
        }
        checked += 1;
    }
    assert!(checked >= 1000, "only {checked} vectors — fixture truncated?");
    println!("replayed {checked} production vectors");
}
